# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgmCWYORUSdIaxgX66otZZDuC2ODvhrb
"""



pip install sarvamai

"""To use the `sarvamai` API, you'll need an API key. Please obtain your API subscription key and store it securely in Colab's secrets manager. You can access the secrets manager from the left panel (🔑 icon). Name the secret `SARVAM_API_KEY`."""

from sarvamai import SarvamAI
from google.colab import userdata

SARVAM_API_KEY = userdata.get('SARVAM_API_KEY')

client = SarvamAI(
    api_subscription_key=SARVAM_API_KEY
)

"""The code requires a `document.pdf` file. For demonstration purposes, I will create a dummy PDF file. **Remember to upload your actual PDF document named `document.pdf` to your Colab environment or adjust the file path in the next code cell.**"""

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

"""After uploading, make sure your PDF is named `document.pdf` or update the code in cell `e080ee50` to use the correct filename."""

# Create a Document Intelligence job
job = client.document_intelligence.create_job(
    language="mr-IN",           # Target language (BCP-47 format)
    output_format="md"          # Output format: "html" or "md" (delivered as ZIP)
)

# Upload your document
job.upload_file("/content/dabholkar-4-m.pdf")

# Start processing
job.start()

# Wait for completion
status = job.wait_until_complete()
print(f"Job completed: {status.job_state}")

# Get processing metrics
metrics = job.get_page_metrics()
print(f"Pages processed: {metrics['pages_processed']}")

# Download the output (ZIP file containing the processed document)
job.download_output("./output.zip")
print("Output saved to ./output.zip")

